export const images = [
    {
        id: 1,
        image: require('@/assets/imgs/nature.jpg'),
        name: 'Nature',
        description: 'Mountains, Forest and Landscapes',
        numberOfWallpapers: 6,
        wallpapers: [
            {
                id: 1,
                image: require('@/assets/imgs/nature/nature1.jpg'),
                name: 'Nature 1',
                description: 'Discover the pure beauty of "Natural Essence" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Natural Essence" for a truly organic transformation in your daily life.',
                tags: ['nature', 'landscape', 'mountains', 'forest'],
            },
            {
                id: 2,
                image: require('@/assets/imgs/nature/nature2.jpg'),
                name: 'Nature 2',
                description: 'Discover the pure beauty of "Natural Essence" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Natural Essence" for a truly organic transformation in your daily life.',
                tags: ['nature', 'landscape', 'mountains', 'forest'],
            },
            {
                id: 3,
                image: require('@/assets/imgs/nature/nature3.jpg'),
                name: 'Nature 3',
                description: 'Discover the pure beauty of "Natural Essence" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Natural Essence" for a truly organic transformation in your daily life.',
                tags: ['nature', 'landscape', 'mountains', 'forest'],
            },
            {
                id: 4,
                image: require('@/assets/imgs/nature/nature4.jpg'),
                name: 'Nature 4',
                description: 'Discover the pure beauty of "Natural Essence" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Natural Essence" for a truly organic transformation in your daily life.',
                tags: ['nature', 'landscape', 'mountains', 'forest'],
            },
            {
                id: 5,
                image: require('@/assets/imgs/nature/nature5.jpg'),
                name: 'Nature 5',
                description: 'Discover the pure beauty of "Natural Essence" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Natural Essence" for a truly organic transformation in your daily life.',
                tags: ['nature', 'landscape', 'mountains', 'forest'],
            },
            {
                id: 6,
                image: require('@/assets/imgs/nature/nature6.jpg'),
                name: 'Nature 6',
                description: 'Discover the pure beauty of "Natural Essence" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Natural Essence" for a truly organic transformation in your daily life.',
                tags: ['nature', 'landscape', 'mountains', 'forest'],
            },
            
        ],
    },
    {
        id: 2,
        image: require('@/assets/imgs/abstract.jpg'),
        name: 'Abstract',
        description: 'Modern Geomentric and artistic designs',
        numberOfWallpapers: 8,
        wallpapers: [
            {
                id: 1,
                image: require('@/assets/imgs/abstract/abstract1.jpg'),
                name: 'Abstract 1',
                description: 'Discover the pure beauty of "Abstract" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Abstract" for a truly organic transformation in your daily life.',
                tags: ['abstract', 'geometric', 'artistic'],
            },
            {
                id: 2,
                image: require('@/assets/imgs/abstract/abstract2.jpg'),
                name: 'Abstract 2',
                description: 'Discover the pure beauty of "Abstract" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Abstract" for a truly organic transformation in your daily life.',
                tags: ['abstract', 'geometric', 'artistic'],
            },
            {
                id: 3,
                image: require('@/assets/imgs/abstract/abstract3.jpg'),
                name: 'Abstract 3',
                description: 'Discover the pure beauty of "Abstract" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Abstract" for a truly organic transformation in your daily life.',
                tags: ['abstract', 'geometric', 'artistic'],
            },
            {
                id: 4,
                image: require('@/assets/imgs/abstract/abstract4.jpg'),
                name: 'Abstract 4',
                description: 'Discover the pure beauty of "Abstract" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Abstract" for a truly organic transformation in your daily life.',
                tags: ['abstract', 'geometric', 'artistic'],
            },
            {
                id: 5,
                image: require('@/assets/imgs/abstract/abstract5.jpg'),
                name: 'Abstract 5',
                description: 'Discover the pure beauty of "Abstract" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Abstract" for a truly organic transformation in your daily life.',
                tags: ['abstract', 'geometric', 'artistic'],
            },
            {
                id: 6,
                image: require('@/assets/imgs/abstract/abstract6.jpg'),
                name: 'Abstract 6',
                description: 'Discover the pure beauty of "Abstract" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Abstract" for a truly organic transformation in your daily life.',
                tags: ['abstract', 'geometric', 'artistic'],
            },
            {
                id: 7,
                image: require('@/assets/imgs/abstract/abstract7.jpg'),
                name: 'Abstract 7',
                description: 'Discover the pure beauty of "Abstract" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Abstract" for a truly organic transformation in your daily life.',
                tags: ['abstract', 'geometric', 'artistic'],
            },
            {
                id: 8,
                image: require('@/assets/imgs/abstract/abstract8.jpg'),
                name: 'Abstract 8',
                description: 'Discover the pure beauty of "Abstract" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Abstract" for a truly organic transformation in your daily life.',
                tags: ['abstract', 'geometric', 'artistic'],
            }
        ],
    },
    {
        id: 3,
        image: require('@/assets/imgs/urban.jpg'),
        name: 'Urban',
        description: 'Cities, architecture and Streets',
        numberOfWallpapers: 7,
        wallpapers: [
            {
                id: 1,
                image: require('@/assets/imgs/urban/urban1.jpg'),
                name: 'Urban 1',
                description: 'Discover the pure beauty of "Urban" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Urban" for a truly organic transformation in your daily life.',
                tags: ['urban', 'architecture', 'streets'],
            },
            {
                id: 2,
                image: require('@/assets/imgs/urban/urban2.jpg'),
                name: 'Urban 2',
                description: 'Discover the pure beauty of "Urban" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Urban" for a truly organic transformation in your daily life.',
                tags: ['urban', 'architecture', 'streets'],
            },
            {
                id: 3,
                image: require('@/assets/imgs/urban/urban3.jpg'),
                name: 'Urban 3',
                description: 'Discover the pure beauty of "Urban" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Urban" for a truly organic transformation in your daily life.',
                tags: ['urban', 'architecture', 'streets'],
            },
            {
                id: 4,
                image: require('@/assets/imgs/urban/urban4.jpg'),
                name: 'Urban 4',
                description: 'Discover the pure beauty of "Urban" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Urban" for a truly organic transformation in your daily life.',
                tags: ['urban', 'architecture', 'streets'],
            },
            {
                id: 5,
                image: require('@/assets/imgs/urban/urban5.jpg'),
                name: 'Urban 5',
                description: 'Discover the pure beauty of "Urban" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Urban" for a truly organic transformation in your daily life.',
                tags: ['urban', 'architecture', 'streets'],
            },
            {
                id: 6,
                image: require('@/assets/imgs/urban/urban6.jpg'),
                name: 'Urban 6',
                description: 'Discover the pure beauty of "Urban" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Urban" for a truly organic transformation in your daily life.',
                tags: ['urban', 'architecture', 'streets'],
            },
            {
                id: 7,
                image: require('@/assets/imgs/urban/urban7.jpg'),
                name: 'Urban 7',
                description: 'Discover the pure beauty of "Urban" – your gateway to authentic, nature-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the natural world. Embrace "Urban" for a truly organic transformation in your daily life.',
                tags: ['urban', 'architecture', 'streets'],
            },
        ],
    },
    {
        id: 4,
        image: require('@/assets/imgs/space.png'),
        name: 'Space',
        description: 'Cosmos, planes and galaxies',
        numberOfWallpapers: 6,
        wallpapers: [
            {
                id: 1,
                image: require('@/assets/imgs/space/space1.jpg'),
                name: 'Space 1',
                description: 'Discover the pure beauty of "Space" – your gateway to authentic, cosmos-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the universe. Embrace "Space" for a truly stellar transformation in your daily life.',
                tags: ['space', 'cosmos', 'galaxies', 'planets'],
            },
            {
                id: 2,
                image: require('@/assets/imgs/space/space2.jpg'),
                name: 'Space 2',
                description: 'Discover the pure beauty of "Space" – your gateway to authentic, cosmos-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the universe. Embrace "Space" for a truly stellar transformation in your daily life.',
                tags: ['space', 'cosmos', 'galaxies', 'planets'],
            },
            {
                id: 3,
                image: require('@/assets/imgs/space/space3.jpg'),
                name: 'Space 3',
                description: 'Discover the pure beauty of "Space" – your gateway to authentic, cosmos-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the universe. Embrace "Space" for a truly stellar transformation in your daily life.',
                tags: ['space', 'cosmos', 'galaxies', 'planets'],
            },
            {
                id: 4,
                image: require('@/assets/imgs/space/space4.jpg'),
                name: 'Space 4',
                description: 'Discover the pure beauty of "Space" – your gateway to authentic, cosmos-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the universe. Embrace "Space" for a truly stellar transformation in your daily life.',
                tags: ['space', 'cosmos', 'galaxies', 'planets'],
            },
            {
                id: 5,
                image: require('@/assets/imgs/space/space5.jpg'),
                name: 'Space 5',
                description: 'Discover the pure beauty of "Space" – your gateway to authentic, cosmos-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the universe. Embrace "Space" for a truly stellar transformation in your daily life.',
                tags: ['space', 'cosmos', 'galaxies', 'planets'],
            },
            {
                id: 6,
                image: require('@/assets/imgs/space/space6.jpg'),
                name: 'Space 6',
                description: 'Discover the pure beauty of "Space" – your gateway to authentic, cosmos-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the universe. Embrace "Space" for a truly stellar transformation in your daily life.',
                tags: ['space', 'cosmos', 'galaxies', 'planets'],
            },
        ],
    },
    {
        id: 5,
        image: require('@/assets/imgs/minimalist.jpg'),
        name: 'Minimalist',
        description: 'Clean, Simple and Elegant',
        numberOfWallpapers: 7,
        wallpapers: [
            {
                id: 1,
                image: require('@/assets/imgs/minimalist/minimalist1.jpg'),
                name: 'Minimalist 1',
                description: 'Discover the pure beauty of "Minimalist" – your gateway to authentic, clean and simple designs. Let this unique collection elevate your senses and connect you with the unrefined elegance of minimalism. Embrace "Minimalist" for a truly elegant transformation in your daily life.',
                tags: ['minimalist', 'clean', 'simple', 'elegant'],
            },
            {
                id: 2,
                image: require('@/assets/imgs/minimalist/minimalist2.jpg'),
                name: 'Minimalist 2',
                description: 'Discover the pure beauty of "Minimalist" – your gateway to authentic, clean and simple designs. Let this unique collection elevate your senses and connect you with the unrefined elegance of minimalism. Embrace "Minimalist" for a truly elegant transformation in your daily life.',
                tags: ['minimalist', 'clean', 'simple', 'elegant'],
            },
            {
                id: 3,
                image: require('@/assets/imgs/minimalist/minimalist3.jpg'),
                name: 'Minimalist 3',
                description: 'Discover the pure beauty of "Minimalist" – your gateway to authentic, clean and simple designs. Let this unique collection elevate your senses and connect you with the unrefined elegance of minimalism. Embrace "Minimalist" for a truly elegant transformation in your daily life.',
                tags: ['minimalist', 'clean', 'simple', 'elegant'],
            },
            {
                id: 4,
                image: require('@/assets/imgs/minimalist/minimalist4.jpg'),
                name: 'Minimalist 4',
                description: 'Discover the pure beauty of "Minimalist" – your gateway to authentic, clean and simple designs. Let this unique collection elevate your senses and connect you with the unrefined elegance of minimalism. Embrace "Minimalist" for a truly elegant transformation in your daily life.',
                tags: ['minimalist', 'clean', 'simple', 'elegant'],
            },
            {
                id: 5,
                image: require('@/assets/imgs/minimalist/minimalist5.jpg'),
                name: 'Minimalist 5',
                description: 'Discover the pure beauty of "Minimalist" – your gateway to authentic, clean and simple designs. Let this unique collection elevate your senses and connect you with the unrefined elegance of minimalism. Embrace "Minimalist" for a truly elegant transformation in your daily life.',
                tags: ['minimalist', 'clean', 'simple', 'elegant'],
            },
            {
                id: 6,
                image: require('@/assets/imgs/minimalist/minimalist6.jpg'),
                name: 'Minimalist 6',
                description: 'Discover the pure beauty of "Minimalist" – your gateway to authentic, clean and simple designs. Let this unique collection elevate your senses and connect you with the unrefined elegance of minimalism. Embrace "Minimalist" for a truly elegant transformation in your daily life.',
                tags: ['minimalist', 'clean', 'simple', 'elegant'],
            },
            {
                id: 7,
                image: require('@/assets/imgs/minimalist/minimalist7.jpg'),
                name: 'Minimalist 7',
                description: 'Discover the pure beauty of "Minimalist" – your gateway to authentic, clean and simple designs. Let this unique collection elevate your senses and connect you with the unrefined elegance of minimalism. Embrace "Minimalist" for a truly elegant transformation in your daily life.',
                tags: ['minimalist', 'clean', 'simple', 'elegant'],
            },
        ],
    },
    {
        id: 6,
        image: require('@/assets/imgs/animals.jpg'),
        name: 'Animals',
        description: 'Wildlife and nature photographys',
        numberOfWallpapers: 6,
        wallpapers: [
            {
                id: 1,
                image: require('@/assets/imgs/animal/animal1.jpg'),
                name: 'Animal 1',
                description: 'Discover the pure beauty of "Animals" – your gateway to authentic, wildlife-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the animal kingdom. Embrace "Animals" for a truly wild transformation in your daily life.',
                tags: ['animals', 'wildlife', 'nature', 'photography'],
            },
            {
                id: 2,
                image: require('@/assets/imgs/animal/animal2.jpg'),
                name: 'Animal 2',
                description: 'Discover the pure beauty of "Animals" – your gateway to authentic, wildlife-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the animal kingdom. Embrace "Animals" for a truly wild transformation in your daily life.',
                tags: ['animals', 'wildlife', 'nature', 'photography'],
            },
            {
                id: 3,
                image: require('@/assets/imgs/animal/animal3.jpg'),
                name: 'Animal 3',
                description: 'Discover the pure beauty of "Animals" – your gateway to authentic, wildlife-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the animal kingdom. Embrace "Animals" for a truly wild transformation in your daily life.',
                tags: ['animals', 'wildlife', 'nature', 'photography'],
            },
            {
                id: 4,
                image: require('@/assets/imgs/animal/animal4.jpg'),
                name: 'Animal 4',
                description: 'Discover the pure beauty of "Animals" – your gateway to authentic, wildlife-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the animal kingdom. Embrace "Animals" for a truly wild transformation in your daily life.',
                tags: ['animals', 'wildlife', 'nature', 'photography'],
            },
            {
                id: 5,
                image: require('@/assets/imgs/animal/animal5.jpg'),
                name: 'Animal 5',
                description: 'Discover the pure beauty of "Animals" – your gateway to authentic, wildlife-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the animal kingdom. Embrace "Animals" for a truly wild transformation in your daily life.',
                tags: ['animals', 'wildlife', 'nature', 'photography'],
            },
            {
                id: 6,
                image: require('@/assets/imgs/animal/animal6.jpg'),
                name: 'Animal 6',
                description: 'Discover the pure beauty of "Animals" – your gateway to authentic, wildlife-inspired experiences. Let this unique collection elevate your senses and connect you with the unrefined elegance of the animal kingdom. Embrace "Animals" for a truly wild transformation in your daily life.',
                tags: ['animals', 'wildlife', 'nature', 'photography'],
            },
        ],
    },
]